### ISSUE TITLE
1.2.0: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [aio-libs/aiosignal#262]
## Long story short
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes oly locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Here is pytest output:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-aiosignal-1.2.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-aiosignal-1.2.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -q
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/aiosignal-1.2.0, configfile: pytest.ini, testpaths: tests/
plugins: cov-3.0.0
collected 0 items / 1 error
/usr/lib64/python3.8/site-packages/coverage/control.py:768: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")

================================================================================== ERRORS ==================================================================================
__________________________________________________________________ ERROR collecting tests/test_signals.py __________________________________________________________________
tests/test_signals.py:19: in <module>
    ???
/usr/lib/python3.8/site-packages/_pytest/mark/structures.py:510: in __getattr__
    warnings.warn(
E   pytest.PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html

---------- coverage: platform linux, python 3.8.12-final-0 -----------
Name                    Stmts   Miss  Cover
-------------------------------------------
aiosignal/__init__.py      15     15     0%
-------------------------------------------
TOTAL                      15     15     0%

========================================================================= short test summary info ==========================================================================
ERROR tests/test_signals.py - pytest.PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for d...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.36s =============================================================================
```

## Expected behaviour
pytest shpuld not fail.

## Actual behaviour
pytest is failig.

## Your environment
python 2.8.12
list of installed modules:
```console
Package                       Version
----------------------------- -------------------
alabaster                     0.7.12
appdirs                       1.4.4
attrs                         21.4.0
Babel                         2.9.1
build                         0.7.0
chardet                       4.0.0
charset-normalizer            2.0.10
coverage                      6.2
cycler                        0.11.0
dbus-python                   1.2.18
distro                        1.6.0
docutils                      0.17.1
extras                        1.0.0
fixtures                      3.0.0
fonttools                     4.28.5
frozenlist                    1.2.0
gpg                           1.16.0-unknown
idna                          3.3
imagesize                     1.3.0
iniconfig                     1.1.1
Jinja2                        3.0.3
kiwisolver                    1.3.2
libcomps                      0.1.18
lit                           13.0.0
lxml                          4.7.1
MarkupSafe                    2.0.1
matplotlib                    3.5.1
meson                         0.60.3
numpy                         1.22.0
olefile                       0.46
packaging                     21.3
pbr                           5.8.0
pep517                        0.12.0
Pillow                        9.0.0
pip                           21.3.1
pluggy                        1.0.0
py                            1.11.0
pycairo                       1.20.1
Pygments                      2.11.2
PyGObject                     3.42.0
pyparsing                     3.0.6
pytest                        6.2.5
pytest-cov                    3.0.0
python-dateutil               2.8.2
pytz                          2021.3
requests                      2.27.1
rpm                           4.17.0
scour                         0.38.2
setuptools                    60.1.0.post20211225
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        4.3.2.dev20220106
sphinxcontrib-applehelp       1.0.2.dev20220108
sphinxcontrib-asyncio         0.3.0
sphinxcontrib-devhelp         1.0.2.dev20220108
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20220108
sphinxcontrib-qthelp          1.0.3.dev20220108
sphinxcontrib-serializinghtml 1.1.5
testtools                     2.5.0
toml                          0.10.2
tomli                         2.0.0
urllib3                       1.26.8
wheel                         0.37.1
```

**Comment by asvetlov** [comment]
You forgot to install `pytest-asyncio` before running tests.

**Comment by kloczek** [comment]
> You forgot to install `pytest-asyncio` before running tests.

Still something is wrong. After add `pytest-asyncio` pytest now fails like below :/
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-aiosignal-1.2.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-aiosignal-1.2.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -q
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 982, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pytest_asyncio/plugin.py", line 112, in pytest_configure
INTERNALERROR>     config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1321, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
```

**Comment by asvetlov** [comment]
An issue was introduced by `pytest-asyncio==0.17` (released today). 
You can either use `pytest-asyncio==0.16` or check out the `aiosignal` master.

**Comment by kloczek** [comment]
I'm using pytest-asyncio 0.17.0.

**Comment by mjpieters** [comment]
Note that 0.17.0 now issues a warning (which has been raised to an error here). We could just add the new switch as the warning suggests; I [did something similar for aiolimiter](https://github.com/mjpieters/aiolimiter/commit/c68b6a8c9c7d4047939e95018d225c3f3959d8c2) earlier.

**Comment by kloczek** [comment]
Just tested new version and all is OK now.
Thank you 👍 
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-aiosignal-1.3.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-aiosignal-1.3.1-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -q
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.15, pytest-7.1.3, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/aiosignal-1.3.1, configfile: setup.cfg, testpaths: tests/
plugins: asyncio-0.20.1, cov-3.0.0
asyncio: mode=strict
collected 11 items

tests/test_signals.py ...........                                                                                                                                    [100%]/usr/lib64/python3.8/site-packages/coverage/control.py:801: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")


---------- coverage: platform linux, python 3.8.15-final-0 -----------
Name                    Stmts   Miss  Cover
-------------------------------------------
aiosignal/__init__.py      15     15     0%
-------------------------------------------
TOTAL                      15     15     0%


============================================================================ 11 passed in 0.08s ===============================================================
```
